const SET_CART = "SET_CART";
const SET_CARDS = "SET_CARDS";
const SET_FAVORITE = "SET_FAVORITE";
const SET_LOADER = "SET_LOADER";
const SET_MODAL = "SET_MODAL";
const CLOSE_MODAL = "CLOSE_MODAL";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const ADD_TO_CART = "ADD_TO_CART";
const CLEAR_CART = "CLEAR_CART";

const types = {
  CLEAR_CART,
  SET_CART,
  SET_CARDS,
  SET_FAVORITE,
  SET_LOADER,
  SET_MODAL,
  REMOVE_FROM_CART,
  ADD_TO_CART,
  CLOSE_MODAL,
};
export default types;
